default: &default
  adapter: postgresql
  encoding: unicode
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fortress_development
  host: localhost
  username: postgres
  password: postgres

test:
  <<: *default
  database: fortress_test
  host: <%= ENV.fetch("POSTGRES_HOST") { localhost } %>
  username: postgres
  password: postgres

production:
  <<: *default
  database: fortress_production
  username: fortress
  password: <%= ENV['FORTRESS_DATABASE_PASSWORD'] %>
