default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { "postgres" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fortress_development
  username: postgres

test:
  <<: *default
  database: fortress_test
  username: postgres

production:
  <<: *default
  database: fortress_production
  username: fortress
