version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - "stephendolan"
    default_assignees:
      - "stephendolan"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"

  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - "stephendolan"
    default_assignees:
      - "stephendolan"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
