name: Main

on: [push, pull_request]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    env:
      RUBYOPT: -W:no-deprecated -W:no-experimental
      RAILS_ENV: test

    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          npm install

      - name: Lint - StandardRB
        run: bundle exec standardrb

      - name: Lint - Prettier
        run: npm run prettier --check .

      - name: Build database
        run: bin/rails db:setup

      - name: Run tests
        run: bundle exec rspec
