name: Main

on: [push]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      PGPORT: ${{ job.services.postgres.ports[5432] }}

    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_PASSWORD: "postgres"
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bin/rails db:setup

      - name: Lint - StandardRB
        run: bundle exec standardrb

      - name: Build database
        run: bin/rails db:setup

      - name: Run tests
        run: bundle exec rspec
